### PR TITLE
Move removal of whitespace from field names to changeNames

### PR DESCRIPTION
**Pull request by ysgit**
@jburkhardt please review and consider merging.

It seems to me that it makes more sense to remove whitespace from the field names in the changeNames function so that if someone doesn't want the field names to be modified at all then this is possible.

### CODE REVIEW

**Comment by jburkhardt** [comment]
Thanks for your suggestion. If you don´t want the field names to be changes at all you can just set argument `changeNames = FALSE` within `getData()`.

**Comment by ysgit** [comment]
Hi Johannes but under the current code, even if you set changeNames =
FALSE, the spaces in the names will still be removed.

**Comment by jburkhardt** [comment]
I can see your point. However in R naming convention whitespace cannot be part of name.
Read more on this here:
https://journal.r-project.org/archive/2012-2/RJournal_2012-2_Baaaath.pdf
You will run into trouble sooner or later if you use whitespace in names.
For instance:
http://stackoverflow.com/questions/12744282/how-to-deal-with-spaces-in-column-names
Moreover changing the code as you suggested causes trouble with productive and running scripts from other users. Hence I will decline your pull request. Anyway thanks for your input!
I hope you understand this decision. If you still want to use whitespace in names you can work on your own fork.

**Comment by ysgit** [comment]
OK, thanks for giving it your attention.

**Pull request closed without merging**
