### PR TITLE
Updated the API to v201502

### PR DESCRIPTION
**Pull request by chipoglesby**
I've updated the API call in getData.R to v201502. I also deleted the csv files in inst/extdata and updated them for v201502 of the API.

### CODE REVIEW

**Comment by jburkhardt** [comment]
Hey Chip,
thanks for replacing the csv files. However I migrated the package already towards the API Version 201502 locally. Currently I am testing locally if everthing works fine, since column names of several report types changed. If everything is fine I will push my migrated version to master. Next time I will accept your push request.
Thanks!
Johannes

**Comment by mbannert** [comment]
Guys, just general remark: Should we support both version. That is either a simple if/else (if it stays simple) or do it the polymorphic way using one getData method apiece for every API version? We could dispatch in a way that prefers the latest API. @jburkhardt do you know whether google supports more than one at a time. I am just thinking of our user's legacy code.

**Comment by chipoglesby** [comment]
@jburkhardt, I have renamed the files. @mbannert, I'm not sure about the if/else statement, I was thinking about making different branches for the two API versions, but your way sounds much easier. It does say that the sunset date will be 14, July 2015: http://goo.gl/4vU6T.

**Comment by chipoglesby** [comment]
Also, this is my first big pull request, so apologies if I make mistakes. I wanted to pitch in because I use this package practically every day at work and I appreciate what you both have done.

**Comment by jburkhardt** [comment]
@chipoglesby Thanks! I really appreciate your contribution! In the meanwhile I already updated all the code and functions on my local master branch in order to work with the new csv formats/names provided by google. With my code changes no manual renaming of the files will be necessary. It works fine with the new API version so far and I will push it soon.

**Comment by jburkhardt** [comment]
@mbannert Great Idea! I will look into it.

**Pull request closed without merging**
